export const datePickerStyle = {
  ".rdrDateDisplayWrapper": { display: "none" },
  ".rdrMonthAndYearPickers": {
    position: "relative",
    left: "-26px",
    width: "196px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
  },
  ".rdrCalendarWrapper": {
    width: "90%",
    height: "346px",
    position: "absolute",
    left: 100,
    right: 0,
  },
  ".rdrDayPassive .rdrDayNumber span": {
    color: "white",
  },
  ".rdrDay:not(.rdrDayPassive) .rdrInRange ~ .rdrDayNumber span, .rdrDay:not(.rdrDayPassive) .rdrSelected ~ .rdrDayNumber span":
    {
      color: "#000000DE",
      gap: 0,
      fontWeight: 400,
      fontSize: "13px",
      LineHeight: "19px",
      display: "flex",
      alignItems: "center",
      textAlign: "center",
      letterSpacing: "0.17px",
    },
  ".rdrMonthName": { display: "none" },
  ".rdrDayNumber span": {
    color: "#000000DE",
    fontWeight: 400,
    fontSize: "13px",
    lineHeight: "19px",
    letterSpacing: "0.17px",
    textAlign: "center",
  },
  ".rdrSelected, .rdrInRange, .rdrStartEdge, .rdrEndEdge": {
    width: "38px",
  },
  ".rdrWeekDays": {
    width: "320px",
    height: "40px",
    gap: "2px",
    padding: 0,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  ".rdrDay:not(.rdrDayPassive) .rdrStartEdge ~ .rdrDayNumber": {
    backgroundImage:
      "linear-gradient(to right, #FFFFFF 0%, #FFFFFF 50%, #F3F6FB 50%, #F3F6FB 100%)",
    height: "36px",
    width: "38px",
    top: 0,
  },
  ".rdrDay:not(.rdrDayPassive) .rdrEndEdge ~ .rdrDayNumber": {
    backgroundImage:
      "linear-gradient(to left, #FFFFFF 0%, #FFFFFF 50%, #F3F6FB 50%, #F3F6FB 100%)",
    height: "36px",
    width: "38px",
    top: 0,
  },
  ".rdrDay:not(.rdrDayPassive) .rdrStartEdge ~ .rdrDayNumber span": {
    zIndex: 2,
    marginRight: "1px",
  },
  ".rdrDay:not(.rdrDayPassive) .rdrEndEdge ~ .rdrDayNumber span": {
    zIndex: 2,
    marginRight: "1px",
  },
  ".rdrDay:not(.rdrDayPassive) .rdrStartEdge.rdrEndEdge ~ .rdrDayNumber": {
    background: "white",
    height: "36px",
    width: "38px",
    top: 0,
  },
  "& .rdrDay": {
    height: "36px",
    width: "36px",
    padding: "0px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    ".rdrInRange": {
      top: "0px",
      backgroundColor: "#F3F6FB",
      height: "36px",
      borderRadius: "0px",
    },
    ".rdrStartEdge": {
      borderRadius: "18px",
      backgroundColor: "#1976D2",
      position: "absolute",
      width: "36px",
      height: "36px",
      left: "0px",
      top: "0px",
      zIndex: 1,
    },
    ".rdrEndEdge": {
      borderRadius: "18px",
      backgroundColor: "#1976D2",
      position: "absolute",
      width: "36px",
      height: "36px",
      left: "0px",
      top: "0px",
      zIndex: 1,
    },
  },
  ".rdrWeekDay": {
    color: "#00000061",
    textTransform: "capitalize",
    height: "40px",
    flexBasis: "36px",
  },
  ".rdrDays": {
    width: "320px",
    height: "264px",
    paddingX: "28px",
    gap: "2px",
    paddingTop: "12px",
    paddingBottom: "26px",
  },
  ".rdrMonthPicker": {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "120px",
  },
  ".rdrYearPicker": {
    marginLeft: "10px",
    paddingRight: "24px",
    width: "60px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  ".rdrPprevButton": {
    marginX: 0,
    marginLeft: 2,
    position: "absolute",
    width: "32px",
    height: "32px",
    left: "218px",
    background: "url('/assets/icons/chevron.svg') no-repeat",
    backgroundPosition: "right 8px center",
    ":hover": {
      background: "url('/assets/icons/chevron.svg') no-repeat",
      backgroundPosition: "right 8px center",
    },
  },
  ".rdrPprevButton i": {
    display: "none",
  },
  ".rdrNextButton": {
    marginRight: "5px",
    position: "relative",
    width: "32px",
    height: "32px",
    left: "18px",
    background: "url('/assets/icons/chevron.svg') no-repeat",
    backgroundPosition: "right 8px center",
    transform: "rotate(180deg)",
    ":hover": {
      background: "url('/assets/icons/chevron.svg') no-repeat",
      backgroundPosition: "right 8px center",
      transform: "rotate(180deg)",
    },
  },
  ".rdrNextButton i": {
    display: "none",
  },
  ".rdrMonthAndYearWrapper": {
    padding: "0px 24px",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  ".rdrMonthAndYearPickers select": {
    textTransform: "capitalize",
    color: "#000000DE",
    minWidth: "60px",
    fontSize: "15px",
    fontWeight: "500",
    lineHeight: "23px",
    height: "32px",
    gap: "0px",
    padding: "0px 0px 4px 0px",
    display: "flex",
    background: "url('/assets/icons/chevron-down.svg') no-repeat",
    backgroundPosition: "right -7px center",
  },
  ".rdrMonthPicker select": {
    backgroundColor: "red",
    width: "130px",
    background: "url('/assets/icons/chevron-down.svg') no-repeat",
    backgroundPosition: "right center",
  },
  ".rdrYearPicker select": {
    backgroundColor: "red",
    width: "90px",
    background: "url('/assets/icons/chevron-down.svg') no-repeat",
    backgroundPosition: "right center",
  },
  ".rdrDayToday:not(.rdrDayPassive) .rdrInRange ~ .rdrDayNumber span, .rdrDayToday:not(.rdrDayPassive) .rdrStartEdge ~ .rdrDayNumber span, .rdrDayToday:not(.rdrDayPassive) .rdrEndEdge ~ .rdrDayNumber span, .rdrDayToday:not(.rdrDayPassive) .rdrSelected ~ .rdrDayNumber span":
    { color: "#242424" },
  ".rdrDayToday:not(.rdrDayPassive) .rdrStartEdge, .rdrDayToday:not(.rdrDayPassive) .rdrEndEdge, .rdrDayToday:not(.rdrDayPassive) .rdrSelected":
    { background: "white", border: "1px solid #1976D2", borderRadius: "18px" },
  ".rdrDay": { width: "36px", height: "36px" },
  borderTopLeftRadius: "30px",
  borderTopRightRadius: "30px",
};
