export type SectorData = {
  id: number;
  name: string;
  provinceId: number;
  cityId: number;
};

const SECTORS_DATA: SectorData[] = [
  {
    id: 1,
    name: "Los Peralejos",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 2,
    name: "Palma Real",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 3,
    name: "Arroyo Manzano",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 4,
    name: "Altos De Arroyo Hondo",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 5,
    name: "Los Ríos",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 6,
    name: "Puerto Isabela",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 7,
    name: "Honduras Del Oeste",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 8,
    name: "Honduras Del Norte",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 9,
    name: "Paseo De Los Indios Ó Parque Mirador Sur",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 10,
    name: "Los Cacicazgos",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 11,
    name: "Renacimiento",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 12,
    name: "Los Restauradores",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 13,
    name: "San Jerónimo",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 14,
    name: "Los Jardines",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 15,
    name: "Jardín Botánico",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 16,
    name: "Nuevo Arroyo Hondo",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 17,
    name: "Cerros De Arroyo Hondo",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 18,
    name: "Viejo Arroyo Hondo",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 19,
    name: "Paraíso",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 20,
    name: "Julieta Morales",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 21,
    name: "Los Prados",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 22,
    name: "El Millón",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 23,
    name: "Mirador Norte",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 24,
    name: "Mirador Sur",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 25,
    name: "Buenos Aires Mirador",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 26,
    name: "Miramar",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 27,
    name: "Tropical Metaldom",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 28,
    name: "Jardines Del Sur",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 29,
    name: "Atala",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 30,
    name: "Bella Vista",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 31,
    name: "Quisqueya",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 32,
    name: "Piantini",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 33,
    name: "La Julia",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 34,
    name: "Nuestra Señora De La Paz",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 35,
    name: "General Antonio Duvergé",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 36,
    name: "30 De Mayo",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 37,
    name: "Cacique",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 38,
    name: "Centro De Los Héroes",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 39,
    name: "Mata Hambre",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 40,
    name: "Ciudad Universitaria",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 41,
    name: "La Esperilla",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 42,
    name: "Ensanche Naco",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 43,
    name: "Centro Olímpico Juan Pablo Duarte",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 44,
    name: "La Fe",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 45,
    name: "La Agustina",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 46,
    name: "Cristo Rey",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 47,
    name: "Jardín Zoológico",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 48,
    name: "La Zurza",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 49,
    name: "Villas Agrícolas",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 50,
    name: "Villa Juana",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 51,
    name: "Miraflores",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 52,
    name: "San Juan Bosco",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 53,
    name: "Gascue",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 54,
    name: "Ciudad Nueva",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 55,
    name: "San Carlos",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 56,
    name: "Villa Consuelo",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 57,
    name: "Ensanche Luperón",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 58,
    name: "Ensanche Capotillo",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 59,
    name: "Simón Bolívar",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 60,
    name: "24 De Abril",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 61,
    name: "Ensanche Espaillat",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 62,
    name: "María Auxiliadora",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 63,
    name: "Mejoramiento Social",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 64,
    name: "Villa Francisca",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 65,
    name: "Ciudad Colonial",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 66,
    name: "Domingo Savio",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 67,
    name: "Gualey",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 68,
    name: "La Isabela",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 69,
    name: "La Hondonada",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 70,
    name: "San Diego",
    provinceId: 1,
    cityId: 1,
  },
  {
    id: 71,
    name: "Villa Duarte",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 72,
    name: "Ensanche Ozama",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 73,
    name: "Los Mina Norte",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 74,
    name: "Los Mina Sur",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 75,
    name: "Alma Rosa",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 76,
    name: "Las Américas",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 77,
    name: "Sans Soucí",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 78,
    name: "Los Tres Brazos-Jardines Del Ozama",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 79,
    name: "Faro A Colón",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 80,
    name: "Los Mameyes",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 81,
    name: "Isabelita",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 82,
    name: "Los Tres Ojos",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 83,
    name: "Villa Faro",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 84,
    name: "Mendoza",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 85,
    name: "Cancino",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 86,
    name: "Los Trinitarios",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 87,
    name: "El Cachón De La Rubia",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 88,
    name: "Cancino Afuera",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 89,
    name: "Cancino Adentro",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 90,
    name: "El Tamarindo",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 91,
    name: "San José De Mendoza",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 92,
    name: "Prado Oriental",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 93,
    name: "Brisa Oriental",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 94,
    name: "Juan López",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 95,
    name: "Hainamosa",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 96,
    name: "El Almirante",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 97,
    name: "Los Frailes",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 98,
    name: "Las Canas",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 99,
    name: "El Cuatro",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 100,
    name: "Los Paredones",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 101,
    name: "San Miguel",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 102,
    name: "La Grúa",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 103,
    name: "El Valiente",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 104,
    name: "La Ureña",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 105,
    name: "San Isidro Adentro",
    provinceId: 2,
    cityId: 2,
  },
  {
    id: 106,
    name: "San Luis",
    provinceId: 2,
    cityId: 3,
  },
  {
    id: 107,
    name: "El Bonito",
    provinceId: 2,
    cityId: 3,
  },
  {
    id: 108,
    name: "San Isidro Afuera",
    provinceId: 2,
    cityId: 3,
  },
  {
    id: 109,
    name: "Batey El Naranjo",
    provinceId: 2,
    cityId: 3,
  },
  {
    id: 110,
    name: "El Puente",
    provinceId: 2,
    cityId: 3,
  },
  {
    id: 111,
    name: "El Cabreto",
    provinceId: 2,
    cityId: 3,
  },
  {
    id: 112,
    name: "El Muelle",
    provinceId: 2,
    cityId: 3,
  },
  {
    id: 113,
    name: "Piragua",
    provinceId: 2,
    cityId: 3,
  },
  {
    id: 114,
    name: "Santo Domingo Country Club",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 115,
    name: "La Altagracia",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 116,
    name: "Engombe",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 117,
    name: "La Rosa",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 118,
    name: "Las Caobas",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 119,
    name: "Alameda",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 120,
    name: "Enriquillo",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 121,
    name: "Buenos Aires De Herrera",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 122,
    name: "Herrera",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 123,
    name: "Zona Industrial Herrera",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 124,
    name: "Juan Pablo Duarte",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 125,
    name: "Finca De Engombe",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 126,
    name: "San Miguel",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 127,
    name: "Bayona",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 128,
    name: "Manoguayabo",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 129,
    name: "Costa Verde",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 130,
    name: "La Ciénaga",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 131,
    name: "Caballona",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 132,
    name: "Palavé",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 133,
    name: "Buenas Noches",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 134,
    name: "Hato Nuevo",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 135,
    name: "Bienvenido",
    provinceId: 2,
    cityId: 4,
  },
  {
    id: 136,
    name: "Villa Mella",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 137,
    name: "Santa Cruz",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 138,
    name: "Sabana Perdida",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 139,
    name: "El Edén",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 140,
    name: "Guaricano",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 141,
    name: "San Felipe",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 142,
    name: "Licey",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 143,
    name: "Mancebo",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 144,
    name: "Mata Gorda",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 145,
    name: "Mata San Juan",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 146,
    name: "Limonal",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 147,
    name: "Punta",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 148,
    name: "Cercadillo",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 149,
    name: "Sierra Prieta",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 150,
    name: "Los Vizcaíno",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 151,
    name: "Buenos Aires",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 152,
    name: "Hoyos Oscuros",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 153,
    name: "Kilómetro 26",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 154,
    name: "Jubileo",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 155,
    name: "Juan Dinga",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 156,
    name: "Duquesa",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 157,
    name: "La Jacagua",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 158,
    name: "Los Cazabes",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 159,
    name: "Higüero Abajo",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 160,
    name: "Cajuilito",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 161,
    name: "La Sabana Del Hato",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 162,
    name: "La Gina",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 163,
    name: "Los Llanos",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 164,
    name: "Rincón Yaco",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 165,
    name: "La Jagua",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 166,
    name: "Loma De Mateo",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 167,
    name: "La Joya O Los Goya",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 168,
    name: "Los Callejones",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 169,
    name: "Los Mameyes",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 170,
    name: "Amor A Dios",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 171,
    name: "Los Cocos",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 172,
    name: "Los Peralejos",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 173,
    name: "Rincón",
    provinceId: 2,
    cityId: 5,
  },
  {
    id: 174,
    name: "La Victoria",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 175,
    name: "Mal Nombre",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 176,
    name: "Punta Larga",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 177,
    name: "Maricao",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 178,
    name: "El Dajao",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 179,
    name: "La Caoba",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 180,
    name: "Palmilla",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 181,
    name: "Primavera",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 182,
    name: "El Corozo",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 183,
    name: "Juan Tomás",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 184,
    name: "El Jobo",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 185,
    name: "La Virgen",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 186,
    name: "San Joaquín",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 187,
    name: "Verdúm",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 188,
    name: "Ferregús",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 189,
    name: "La Culata",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 190,
    name: "Mata Mamón",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 191,
    name: "San Mateo",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 192,
    name: "La Guabina",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 193,
    name: "Los Tapia (El Ocho)",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 194,
    name: "Los Potrazos",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 195,
    name: "Rincón Dorado",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 196,
    name: "Los Rosario",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 197,
    name: "Los Genaro",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 198,
    name: "El Siete",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 199,
    name: "Cabón",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 200,
    name: "Santana",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 201,
    name: "Aguacate Adentro",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 202,
    name: "El Higüerito",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 203,
    name: "El Ocho",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 204,
    name: "La Bomba",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 205,
    name: "Guayabo",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 206,
    name: "Batey Guanuma",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 207,
    name: "Mata Redonda",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 208,
    name: "La Gina (La Tita)",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 209,
    name: "El Hato De Sanguíneo",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 210,
    name: "Hacienda Estrella",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 211,
    name: "El 11 De Hacienda Estrella",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 212,
    name: "El 10 De Hacienda Estrella",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 213,
    name: "La Campaña",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 214,
    name: "Los Morenos",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 215,
    name: "La Ceiba",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 216,
    name: "La Piña",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 217,
    name: "Los Castillos",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 218,
    name: "Los Mercedes",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 219,
    name: "Los Mambruses",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 220,
    name: "La Jaiba",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 221,
    name: "Rancho Arriba-Cabón",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 222,
    name: "Cruce De Gina",
    provinceId: 2,
    cityId: 6,
  },
  {
    id: 223,
    name: "Boca Chica",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 224,
    name: "Andrés",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 225,
    name: "Cruce De Boca Chica",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 226,
    name: "El Limón",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 227,
    name: "Kilómetro 36, Carretera Mella",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 228,
    name: "Los Paredones De Andrés",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 229,
    name: "Batey Jubey",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 230,
    name: "La Malena",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 231,
    name: "La Cucama",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 232,
    name: "La Tumba",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 233,
    name: "La Ciguapa",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 234,
    name: "La Bocaina",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 235,
    name: "Los Bancos De Arena",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 236,
    name: "La Borda",
    provinceId: 2,
    cityId: 7,
  },
  {
    id: 237,
    name: "La Caleta",
    provinceId: 2,
    cityId: 8,
  },
  {
    id: 238,
    name: "El Valiente",
    provinceId: 2,
    cityId: 8,
  },
  {
    id: 239,
    name: "Torre B",
    provinceId: 2,
    cityId: 8,
  },
  {
    id: 240,
    name: "Campo Lindo",
    provinceId: 2,
    cityId: 8,
  },
  {
    id: 241,
    name: "La Cien Mil-La Piedra",
    provinceId: 2,
    cityId: 8,
  },
  {
    id: 242,
    name: "Aeropuerto Internacional",
    provinceId: 2,
    cityId: 8,
  },
  {
    id: 243,
    name: "El Cachimbo",
    provinceId: 2,
    cityId: 8,
  },
  {
    id: 244,
    name: "Guerra Centro",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 245,
    name: "El Toro",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 246,
    name: "La Piedra",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 247,
    name: "El Fao",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 248,
    name: "El Mamón",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 249,
    name: "La Mujarra (Mojarra)",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 250,
    name: "La Corcobada (Corcovada)",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 251,
    name: "El Viso",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 252,
    name: "Concordia",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 253,
    name: "La Filipina",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 254,
    name: "El Mamey",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 255,
    name: "La Joya",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 256,
    name: "Los Barreros",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 257,
    name: "La Guama",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 258,
    name: "Mata Barraco",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 259,
    name: "Santa Lucía",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 260,
    name: "Tierra Blanca",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 261,
    name: "El Alto",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 262,
    name: "El Cachón (Los Cachones)",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 263,
    name: "La Batata",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 264,
    name: "El Peje",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 265,
    name: "Ahorca Los Perros",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 266,
    name: "Cruce De Guerra",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 267,
    name: "La Estancia",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 268,
    name: "Bejucal",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 269,
    name: "Los Berroa",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 270,
    name: "La Caoba",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 271,
    name: "La Pluma",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 272,
    name: "El Cajuilito",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 273,
    name: "El Coquito",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 274,
    name: "La Culebra",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 275,
    name: "Proyecto Cabreto",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 276,
    name: "Los Cocos",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 277,
    name: "Cuenca",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 278,
    name: "La Jagüita",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 279,
    name: "Valentín",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 280,
    name: "Las Parras",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 281,
    name: "La Reforma",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 282,
    name: "El Porrito O Pomito",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 283,
    name: "La Granja",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 284,
    name: "La Barías",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 285,
    name: "Cerro Cabra",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 286,
    name: "El Cea",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 287,
    name: "Santa María",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 288,
    name: "Poco Agua",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 289,
    name: "La Picadora",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 290,
    name: "Capacito",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 291,
    name: "Bella Vista",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 292,
    name: "Mata Vaca",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 293,
    name: "Los Marenos",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 294,
    name: "La Piña",
    provinceId: 2,
    cityId: 9,
  },
  {
    id: 295,
    name: "Estorga",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 296,
    name: "Batey II O Hato Viejo II",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 297,
    name: "El Limón",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 298,
    name: "Hato Viejo",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 299,
    name: "La Gina",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 300,
    name: "Kilómetro 36B",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 301,
    name: "Batey Amelia",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 302,
    name: "Mata La Piedra",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 303,
    name: "Juana Jico",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 304,
    name: "La Catalina",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 305,
    name: "Ismael Jiménez O Las Garzas",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 306,
    name: "Los Urbanos",
    provinceId: 2,
    cityId: 10,
  },
  {
    id: 307,
    name: "Savica",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 308,
    name: "Canta La Rana O Barriolandia",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 309,
    name: "Pueblo Nuevo",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 310,
    name: "Las Mercedes",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 311,
    name: "Los Libertadores",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 312,
    name: "Altos De Chavón",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 313,
    name: "Los Americanos (Los Ángeles)",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 314,
    name: "Nuevo Amanecer",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 315,
    name: "Nazareno O Manzanero",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 316,
    name: "Lebrón",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 317,
    name: "La Unión",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 318,
    name: "La Fe",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 319,
    name: "La Piña",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 320,
    name: "Valle Encantado",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 321,
    name: "Residencial Los Cerros",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 322,
    name: "La Esperanza",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 323,
    name: "Residencial Los Hidalgos",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 324,
    name: "Paraíso",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 325,
    name: "Santa Rosa",
    provinceId: 2,
    cityId: 11,
  },
  {
    id: 326,
    name: "Palmarejo",
    provinceId: 2,
    cityId: 12,
  },
  {
    id: 327,
    name: "Santa Rosa",
    provinceId: 2,
    cityId: 12,
  },
  {
    id: 328,
    name: "Palmarejito",
    provinceId: 2,
    cityId: 12,
  },
  {
    id: 329,
    name: "Las Flores",
    provinceId: 2,
    cityId: 12,
  },
  {
    id: 330,
    name: "Santa Bárbara",
    provinceId: 2,
    cityId: 12,
  },
  {
    id: 331,
    name: "Los Coquitos",
    provinceId: 2,
    cityId: 12,
  },
  {
    id: 332,
    name: "Cerinca",
    provinceId: 2,
    cityId: 12,
  },
  {
    id: 333,
    name: "Villa Linda",
    provinceId: 2,
    cityId: 12,
  },
  {
    id: 334,
    name: "Pantoja",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 335,
    name: "Urbanización Don Gregorio",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 336,
    name: "Villa El Palmar",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 337,
    name: "Urbanización Proyecto Invi-Cea",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 338,
    name: "Villa Morada",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 339,
    name: "Urbanización Villa Pantoja",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 340,
    name: "La Redención",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 341,
    name: "Las Colinas O Los Cocos",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 342,
    name: "Pantoja I",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 343,
    name: "Vista Verde",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 344,
    name: "José Contreras",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 345,
    name: "Reparto Samaria",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 346,
    name: "Residencial Don Miguel",
    provinceId: 2,
    cityId: 13,
  },
  {
    id: 347,
    name: "Pedro Brand",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 348,
    name: "Los Cocos (Kilómetro 28)",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 349,
    name: "El Catalán",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 350,
    name: "Los Corozos",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 351,
    name: "San Miguel",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 352,
    name: "Mata De Iglesia",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 353,
    name: "Piedra Gorda",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 354,
    name: "La Montosa",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 355,
    name: "La Polonia",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 356,
    name: "El Platón",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 357,
    name: "Frasquito Gómez",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 358,
    name: "El Puerto",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 359,
    name: "Santa Cruz",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 360,
    name: "Hato Viejo",
    provinceId: 2,
    cityId: 14,
  },
  {
    id: 361,
    name: "La Guáyiga",
    provinceId: 2,
    cityId: 15,
  },
  {
    id: 362,
    name: "Batey Palamara",
    provinceId: 2,
    cityId: 15,
  },
  {
    id: 363,
    name: "Los García",
    provinceId: 2,
    cityId: 15,
  },
  {
    id: 364,
    name: "El Pedregal",
    provinceId: 2,
    cityId: 15,
  },
  {
    id: 365,
    name: "Yacó",
    provinceId: 2,
    cityId: 15,
  },
  {
    id: 366,
    name: "Proyecto Los Guardias",
    provinceId: 2,
    cityId: 15,
  },
  {
    id: 367,
    name: "La Cuaba",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 368,
    name: "Los Aguacates",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 369,
    name: "Salamanca",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 370,
    name: "Arroyo Indio",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 371,
    name: "La Piña",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 372,
    name: "El Convento",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 373,
    name: "La Maleza",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 374,
    name: "La Estancia",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 375,
    name: "Sabana Al Medio",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 376,
    name: "Higüero",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 377,
    name: "Los Jobos De Matúa",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 378,
    name: "Higuamo",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 379,
    name: "Suardí",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 380,
    name: "Hojas Anchas",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 381,
    name: "El Limón",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 382,
    name: "La Isabela Arriba",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 383,
    name: "Bañadero",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 384,
    name: "El Cachón",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 385,
    name: "Los Genaro",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 386,
    name: "Sabana Mina",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 387,
    name: "El Cachimbo",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 388,
    name: "Mala Vuelta",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 389,
    name: "Victoriano",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 390,
    name: "Arroyo Mina",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 391,
    name: "Loma De Galán",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 392,
    name: "La Malenita",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 393,
    name: "La Malena",
    provinceId: 2,
    cityId: 16,
  },
  {
    id: 394,
    name: "Los Pilones O Los Pilares",
    provinceId: 2,
    cityId: 16,
  },
];

export default SECTORS_DATA;
